name: discord
version: 0.10.4+dev
description: A Discord library for Dart
author: Hackzzila <admin@hackzzila.com>
homepage: https://hackzzila.github.io/Discord-Dart/
dependencies:
  http: ">=0.11.3+9 <0.12.0"
  events: ">=0.1.2+1 <0.2.0"
dev_dependencies:
  dart_style:
